1. Create a NumPy array of integers from 1 to 10

In [ ]:
import numpy as np

In [ ]:
arr1=np.arange(1,11)

In [ ]:
arr1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Create a 2x3 NumPy array filled with zeros

In [ ]:
arr2=np.zeros((2,3))

In [ ]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

3. Create a NumPy array of even numbers from 2 to 20.

In [ ]:
arr3=np.arange(2,21,2)

In [ ]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4. Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two array

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])




In [ ]:
arr1+arr2

array([5, 7, 9])

In [ ]:
arr2-arr1

array([3, 3, 3])

In [ ]:
arr1-arr2

array([-3, -3, -3])

In [ ]:
arr1*arr2

array([ 4, 10, 18])

In [ ]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

5. Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.

In [ ]:
arr3=np.random.randint(0,100,100)

In [ ]:
arr3

array([29, 95,  0,  1, 94, 44, 49, 86, 60, 39, 95, 90, 12, 37, 21, 10, 51,
       92, 96, 18, 30, 74, 85, 56, 82, 72, 81, 78, 78, 64, 19, 29, 71, 46,
       64, 34, 42, 90, 53, 52, 31, 35, 41,  2, 84, 30, 72, 69, 18, 48, 11,
       81, 53, 22, 88, 93,  8, 15, 67, 60, 64, 97, 88, 77,  5,  4, 38,  8,
       95, 99, 12,  8, 50, 60, 73,  8, 30, 69, 18, 71, 77,  1, 20, 76, 64,
       75, 29, 71, 43, 83, 78, 51, 63, 44,  0, 16, 69, 64, 49, 40])

In [ ]:
arr3.mean()

51.34

In [ ]:
median=np.median(arr3)
print(median)

52.5


In [ ]:
std_dev=np.std(arr3)
print(std_dev)

29.29102934346965


6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).

In [ ]:
arr4=np.random.randint(0,20,12)

In [ ]:
arr4

array([18,  3,  7,  8,  2,  4, 10, 19, 11, 13,  2, 16])

In [ ]:
arr4.reshape(3,4)

array([[18,  3,  7,  8],
       [ 2,  4, 10, 19],
       [11, 13,  2, 16]])

7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.

In [ ]:
 arr = np.array([1, 2, 3, 4, 5])


In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

8. Create a 5x5 identity matrix using NumPy.

In [ ]:
arr5=np.eye(5,5)

In [ ]:
arr5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6]

In [ ]:
 a = np.array([1, 2, 3])
 b = np.array([4, 5, 6])


In [ ]:
a*b

array([ 4, 10, 18])

10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.

In [ ]:
arr6=np.arange(0,21)

In [ ]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
arr6.reshape(3,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [ ]:
arr6.max()

20

In [ ]:
arr6.min()

0

11.Concatenate two random NumPy arrays horizontally and vertically.

In [ ]:
a=np.zeros((3,3))

In [ ]:
b=np.ones((3,3))

In [ ]:
import numpy as np
np.concatenate((a,b),axis=1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

12.Given a 2D NumPy array, calculate the sum of each row and each column
separately.

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                 [9, 10,11,12]])

In [ ]:
np.sum(arr, axis=1)

array([10, 26, 42])

In [ ]:
np.sum(arr,axis=0)

array([15, 18, 21, 24])

13.Find the common elements between two NumPy arrays.

In [ ]:
arr1=(1,2,5,6,8,9,20)
arr2=(4,7,3,10,20,21,15)

In [ ]:
np.intersect1d(arr1,arr2)

array([20])

14.Replace all negative values in a NumPy array with zeros

In [ ]:
arr=(-1,2,3,-4,-5)

In [ ]:
np.where(arr<0,0,arr)

array([0, 2, 3, 0, 0])

15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order

In [ ]:

import numpy as np
arr=np.random.randint(1,101,size=10)
arr.sort()
print(arr)

[11 26 47 63 66 69 73 82 85 99]


16.Calculate the element-wise absolute difference between two NumPy
arrays.

In [ ]:

import numpy as np
arr1=np.array([8,10,19,15])
arr2=np.array([6,8,10,12])

In [ ]:
abs_diff=np.abs(arr1-arr2)
print(abs_diff)

[2 2 9 3]


17.Given a 2D NumPy array, extract the first row and the last column

In [ ]:

arr1=np.array([[10, 1, 14, 16, 18, 20],

[22,24,26,28,30,32],

[34,36,38,40,42,44],

[46,48,50,52,54,56],

[58,60,62,64,66,68],

[70,72,74,76,78,80]])

In [ ]:
arr1

array([[10,  1, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [ ]:
arr1[0]

array([10,  1, 14, 16, 18, 20])

In [ ]:
arr1[0:,[5]]

array([[20],
       [32],
       [44],
       [56],
       [68],
       [80]])

18.Slice a 1D NumPy array to get every other element.

In [ ]:
arr=(20,11,12,21,19,25,23,30,50)

In [ ]:
arr[::2]

(20, 12, 19, 23, 50)

In [ ]:
arr[1:5]

(11, 12, 21, 19)

19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.

In [ ]:
 import numpy as np
arr4= np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12],
 [13, 14, 15, 16]])
subarray=arr4[1:3,2:4]
print(subarray)

[[ 7  8]
 [11 12]]


20.Reverse a 1D NumPy array using slicing

In [ ]:

import numpy as np
arr= np.array([1, 2, 3, 4, 5])

In [ ]:
reversed_array = arr[::-1]
print(reversed_array)

[5 4 3 2 1]
